name: graphics_news
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0
  carousel_slider: ^4.0.0
  dots_indicator: 
  video_player: ^2.1.12
  chewie: ^1.2.2
  webview_flutter: ^2.0.12
  http:
  email_validator: ^2.0.1
  intl: ^0.17.0
  country_list_pick: ^1.0.1+5
  shared_preferences: ^2.0.6
  audioplayers: ^0.20.1
  youtube_player_flutter: ^8.0.0
  flutter_screenutil: ^5.0.0+2
  flutter_tts:
  syncfusion_flutter_pdfviewer:
  permission_handler:
  dio: ^4.0.0
  path_provider:
  objectdb:
  provider:
  epub_viewer: ^0.2.4




dev_dependencies:
  flutter_test:
    sdk: flutter




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - asset/

  fonts:
    - family: Customicons
      fonts:
        - asset: icons/Customicons.ttf

    - family: SpeakerIcon
      fonts:
        - asset: icons/SpeakerIcon.ttf

    - family: BookmarkIcon
      fonts:
        - asset: icons/BookmarkIcon.ttf

    - family: ContactLeftIcon
      fonts:
        - asset: icons/ContactLeftIcon.ttf

    - family: DownloadsLeftIcon   
      fonts:
        - asset: icons/DownloadsLeftIcon.ttf

    - family: FAQLeftIcon   
      fonts:
        - asset: icons/FAQLeftIcon.ttf

    - family: LogoutLeftIcon   
      fonts:
        - asset: icons/LogoutLeftIcon.ttf

    - family: MagazineLeftIcon   
      fonts:
        - asset: icons/MagazineLeftIcon.ttf

    - family: NewsLeftIcon   
      fonts:
        - asset: icons/NewsLeftIcon.ttf

    - family: ProfileLeftIcon   
      fonts:
        - asset: icons/ProfileLeftIcon.ttf

    - family: ReferLeftIcon   
      fonts:
        - asset: icons/ReferLeftIcon.ttf

    - family: ServicesLeftIcon   
      fonts:
        - asset: icons/ServicesLeftIcon.ttf

    - family: SubscriptionLeftIcon   
      fonts:
        - asset: icons/SubscriptionLeftIcon.ttf
    
    - family: DOBIcon
      fonts:
        - asset: icons/DOBIcon.ttf

    - family: HomeCalanderIcon
      fonts:
        - asset: icons/HomeCalanderIcon.ttf

    - family: ListingCalanderIcon
      fonts:
        - asset: icons/ListingCalanderIcon.ttf
               
    - family: MenuIcon
      fonts:
        - asset: icons/MenuIcon.ttf
           
    - family: UncheckIcon
      fonts:
        - asset: icons/UncheckIcon.ttf    

    - family: SettingIcon
      fonts:
        - asset: icons/SettingIcon.ttf
   
    - family: AboutIcon
      fonts:
        - asset: icons/AboutIcon.ttf  

    - family: FAQIcon
      fonts:
        - asset: icons/FAQIcon.ttf 

    - family: BookIcon
      fonts:
        - asset: icons/BookIcon.ttf  

    - family: ContactIcon
      fonts:
        - asset: icons/ContactIcon.ttf 

    - family: DateCalenderIcon
      fonts:
        - asset: icons/DateCalenderIcon.ttf   

    - family: EyeIcon
      fonts:
        - asset: icons/EyeIcon.ttf  

    - family: FBIcon
      fonts:
        - asset: icons/FBIcon.ttf    

    - family: HomeIcon
      fonts:
        - asset: icons/HomeIcon.ttf   

    - family: TwitterIcon
      fonts:
        - asset: icons/TwitterIcon.ttf  

    - family: YoutubeIcon
      fonts:
        - asset: icons/YoutubeIcon.ttf            


    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
          weight: 500
        - asset: fonts/Poppins-Light.ttf
          weight: 100
        - asset: fonts/Poppins-Medium.ttf
          weight: 300
        - asset: fonts/Poppins-Regular.ttf
          weight: 200
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 400

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
