/// Flutter icons BookIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BookIcon
///      fonts:
///       - asset: fonts/BookIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class BookIcon {
  BookIcon._();

  static const _kFontFam = 'BookIcon';
  static const String? _kFontPkg = null;

  static const IconData book_without_background = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
