/// Flutter icons ContactLeftIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ContactLeftIcon
///      fonts:
///       - asset: fonts/ContactLeftIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ContactLeftIcon {
  ContactLeftIcon._();

  static const _kFontFam = 'ContactLeftIcon';
  static const String? _kFontPkg = null;

  static const IconData contact_us = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
