/// Flutter icons DOBIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DOBIcon
///      fonts:
///       - asset: fonts/DOBIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class DOBIcon {
  DOBIcon._();

  static const _kFontFam = 'DOBIcon';
  static const String? _kFontPkg = null;

  static const IconData date_of_birth_calender = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
