/// Flutter icons DateCalenderIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DateCalenderIcon
///      fonts:
///       - asset: fonts/DateCalenderIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class DateCalenderIcon {
  DateCalenderIcon._();

  static const _kFontFam = 'DateCalenderIcon';
  static const String? _kFontPkg = null;

  static const IconData date_calender = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
