/// Flutter icons DownloadsLeftIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DownloadsLeftIcon
///      fonts:
///       - asset: fonts/DownloadsLeftIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class DownloadsLeftIcon {
  DownloadsLeftIcon._();

  static const _kFontFam = 'DownloadsLeftIcon';
  static const String? _kFontPkg = null;

  static const IconData my_downloads = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
