/// Flutter icons FAQIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FAQIcon
///      fonts:
///       - asset: fonts/FAQIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class FAQIcon {
  FAQIcon._();

  static const _kFontFam = 'FAQIcon';
  static const String? _kFontPkg = null;

  static const IconData faq = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
