/// Flutter icons InstaIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  InstaIcon
///      fonts:
///       - asset: fonts/InstaIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class InstaIcon {
  InstaIcon._();

  static const _kFontFam = 'InstaIcon';
  static const String? _kFontPkg = null;

  static const IconData instagram = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
