/// Flutter icons ProfileLeftIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ProfileLeftIcon
///      fonts:
///       - asset: fonts/ProfileLeftIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ProfileLeftIcon {
  ProfileLeftIcon._();

  static const _kFontFam = 'ProfileLeftIcon';
  static const String? _kFontPkg = null;

  static const IconData my_profile = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
